<!DOCTYPE html>
<html lang="ko" data-theme="dark">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>디자인 목업 — Design Mockup</title>
<link rel="stylesheet" href="../assets/site.css">
<style>
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
:root{
  --bg:#0d0d14;
  --bg2:#12121c;
  --surface:#181825;
  --surface2:#1e1e30;
  --surface3:#282845;
  --border:#2a2a40;
  --border2:#3a3a55;
  --text:#F5F0E8;
  --text2:#A89A8F;
  --text3:#948779;
  --accent:#E8965A;
  --accent2:#F0B088;
  --accent-dim:rgba(232,150,90,0.12);
  --accent-glow:rgba(232,150,90,0.06);
  --error:#f87171;
  --success:#4ade80;
  --warn:#fbbf24;
  --info:#38bdf8;
  --radius:14px;
  --radius-sm:8px;
  --radius-lg:20px;
  --transition:0.25s cubic-bezier(.4,0,.2,1);
  --mono:'SF Mono','Cascadia Code','Consolas',monospace;
}
[data-theme="light"]{
  --bg:#faf9f7;--bg2:#f2f0ec;--surface:#ffffff;--surface2:#f5f3ef;--surface3:#ebe7e0;--border:#e0dcd4;--border2:#cfc9bf;--text:#1a1a24;--text2:#5a5248;--text3:#6b6259;--accent:#9A4A0B;--accent2:#8a4510;--accent-dim:rgba(154,74,11,0.1);--accent-glow:rgba(154,74,11,0.06);--error:#b91c1c;--success:#146B32;--warn:#7A4A05;--info:#0369a1;
}
  .theme-toggle{position:fixed;top:12px;right:12px;z-index:60;min-width:44px;min-height:44px;padding:0 12px;
    background:var(--surface);color:var(--text2);border:1px solid var(--border);border-radius:10px;font-size:13px;font-weight:600;cursor:pointer}
  .theme-toggle:hover{border-color:var(--accent);color:var(--text)}
  .theme-toggle:focus-visible{outline:2px solid var(--accent);outline-offset:2px}

html{font-size:16px;scroll-behavior:smooth}
body{
  font-family:'Pretendard Variable','Pretendard',-apple-system,'Segoe UI',system-ui,sans-serif;
  background:var(--bg);
  color:var(--text);
  line-height:1.7;
  min-height:100vh;
  -webkit-font-smoothing:antialiased;
}
::-webkit-scrollbar{width:6px;height:6px}
::-webkit-scrollbar-track{background:transparent}
::-webkit-scrollbar-thumb{background:var(--border2);border-radius:3px}
a{color:var(--accent2);text-underline-offset:3px}
a:hover{color:var(--text)}
a:focus-visible,summary:focus-visible{
  outline:3px solid var(--accent);
  outline-offset:4px;
  border-radius:4px;
}
.page{max-width:1280px;margin:0 auto;padding:0 24px}
section{padding:72px 0}
section+section{border-top:1px solid var(--border)}

/* HERO — 기존 페이지의 중앙 정렬·그라디언트 머리 구조 유지 */
.hero{
  padding:60px 0 80px;
  text-align:center;
  background:radial-gradient(ellipse at 50% 0%,rgba(232,150,90,0.08) 0%,transparent 60%);
}
.hero-badge{
  display:inline-block;
  padding:6px 18px;
  border-radius:100px;
  background:var(--accent-dim);
  color:var(--accent);
  font-size:13px;
  font-weight:600;
  letter-spacing:0.05em;
  text-transform:uppercase;
  margin-bottom:24px;
}
.hero h1{
  font-size:clamp(2.5rem,5vw + 1rem,4.5rem);
  font-weight:800;
  line-height:1.1;
  letter-spacing:-0.03em;
  background:linear-gradient(135deg,#fff 0%,var(--accent) 50%,var(--accent2) 100%);
  -webkit-background-clip:text;
  -webkit-text-fill-color:transparent;
  background-clip:text;
  margin-bottom:20px;
}
.hero p{
  font-size:1.125rem;
  color:var(--text2);
  max-width:760px;
  margin:0 auto;
  line-height:1.7;
}
.hero-meta{
  display:flex;
  justify-content:center;
  flex-wrap:wrap;
  gap:10px;
  margin-top:28px;
}
.pill{
  padding:6px 12px;
  border:1px solid var(--border2);
  border-radius:100px;
  color:var(--text2);
  background:var(--surface);
  font-size:13px;
}

/* SECTION */
.section-label{
  font-size:13px;
  font-weight:600;
  color:var(--accent);
  letter-spacing:0.1em;
  text-transform:uppercase;
  margin-bottom:12px;
}
.section-title{
  font-size:clamp(1.75rem,3vw,2.5rem);
  font-weight:700;
  line-height:1.2;
  margin-bottom:8px;
}
.section-desc{
  font-size:1rem;
  color:var(--text2);
  max-width:760px;
  line-height:1.7;
  margin-bottom:40px;
}
.subhead{
  font-size:1.25rem;
  line-height:1.35;
  margin:36px 0 16px;
}
.eyebrow{
  color:var(--accent);
  font-family:var(--mono);
  font-size:12px;
  font-weight:700;
  letter-spacing:0.08em;
  margin-bottom:8px;
}

/* GRID / CARD */
.grid-2{display:grid;grid-template-columns:repeat(2,1fr);gap:24px}
.grid-3{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}
.grid-4{display:grid;grid-template-columns:repeat(4,1fr);gap:16px}
.grid-2>*,.grid-3>*,.grid-4>*,.compare>*{min-width:0}
.card{
  background:var(--surface);
  border:1px solid var(--border);
  border-radius:var(--radius-lg);
  padding:28px;
  transition:border-color var(--transition),transform var(--transition);
}
.card:hover{border-color:var(--border2);transform:var(--dk-hover-move, translateY(-1px))}
.card-title{
  font-size:1.0625rem;
  font-weight:700;
  line-height:1.35;
  margin-bottom:12px;
  display:flex;
  align-items:center;
  gap:10px;
}
.card-title .dot{
  width:8px;
  height:8px;
  border-radius:50%;
  background:var(--accent);
  flex:0 0 auto;
}
.card p,.card li{font-size:15px;color:var(--text2)}
.card ul{padding-left:20px;display:grid;gap:8px}
.principle-card{display:flex;flex-direction:column;min-height:230px}
.principle-card .card-source{
  margin-top:auto;
  padding-top:20px;
  font-size:13px;
  font-weight:700;
}
.num{
  display:inline-flex;
  align-items:center;
  justify-content:center;
  width:28px;
  height:28px;
  border-radius:8px;
  flex:0 0 auto;
  background:var(--accent-dim);
  color:var(--accent);
  font-size:13px;
  font-weight:800;
}

/* WORKFLOW */
.workflow{
  display:flex;
  align-items:center;
  justify-content:center;
  gap:0;
  flex-wrap:wrap;
  margin:0 auto 8px;
}
.workflow-item{
  font-size:14px;
  font-weight:600;
  padding:8px 20px;
  border-radius:100px;
  border:1px solid var(--border);
  color:var(--text3);
  background:var(--surface);
}
.workflow-item.active{
  background:var(--accent-dim);
  border-color:var(--accent);
  color:var(--accent);
}
.workflow-arrow{color:var(--text3);font-size:18px;margin:0 8px;user-select:none}

/* TABLE */
.table-wrap{
  overflow-x:auto;
  -webkit-overflow-scrolling:touch;
  max-width:100%;
  border-radius:var(--radius);
  border:1px solid var(--border);
}
.table-wrap>table{min-width:max-content}
table{width:100%;border-collapse:collapse;font-size:14px}
thead{background:var(--surface2)}
th{
  padding:14px 16px;
  text-align:left;
  font-weight:600;
  font-size:13px;
  color:var(--text2);
  letter-spacing:0.04em;
  text-transform:uppercase;
  white-space:nowrap;
  border-bottom:1px solid var(--border);
}
td{padding:13px 16px;border-bottom:1px solid var(--border);vertical-align:top;color:var(--text2)}
tbody tr:last-child td{border-bottom:none}
tbody tr:hover{background:var(--accent-glow)}

/* CODE / NOTE */
code{
  font-family:var(--mono);
  font-size:0.9em;
  background:var(--surface2);
  padding:2px 6px;
  border-radius:4px;
  color:var(--accent2);
  overflow-wrap:anywhere;
}
pre{
  overflow-x:auto;
  max-width:100%;
  padding:20px;
  background:var(--bg2);
  border:1px solid var(--border);
  border-radius:var(--radius);
  color:var(--text2);
  line-height:1.65;
}
pre code{white-space:pre;background:transparent;padding:0;color:inherit;overflow-wrap:normal}
.note{
  padding:18px 20px;
  border-left:3px solid var(--accent);
  background:var(--accent-glow);
  border-radius:0 var(--radius-sm) var(--radius-sm) 0;
  color:var(--text2);
  margin:20px 0;
}
.note strong{color:var(--text)}

/* COMPARE */
.compare{display:grid;grid-template-columns:1fr 1fr;gap:20px}
.compare-panel{padding:28px;border-radius:var(--radius-lg)}
.compare-bad{background:rgba(248,113,113,0.06);border:1px solid rgba(248,113,113,0.28)}
.compare-good{background:rgba(74,222,128,0.06);border:1px solid rgba(74,222,128,0.28)}
.compare-label{
  font-size:12px;
  font-weight:800;
  letter-spacing:0.1em;
  text-transform:uppercase;
  margin-bottom:12px;
}
.compare-bad .compare-label{color:var(--error)}
.compare-good .compare-label{color:var(--success)}
.compare-panel h3{font-size:1.125rem;margin-bottom:10px}
.compare-panel p,.compare-panel li{font-size:15px;color:var(--text2)}
.compare-panel ul{padding-left:20px;display:grid;gap:8px;margin-top:14px}

/* CHECKLIST */
.checklist{list-style:none;display:grid;gap:12px}
.checklist li{
  display:flex;
  align-items:flex-start;
  gap:12px;
  padding:14px 16px;
  border:1px solid var(--border);
  border-radius:var(--radius-sm);
  background:var(--surface);
  color:var(--text2);
  font-size:14px;
}
.check{
  display:inline-flex;
  align-items:center;
  justify-content:center;
  width:22px;
  height:22px;
  flex:0 0 auto;
  border:2px solid var(--accent);
  border-radius:6px;
  color:var(--accent);
  font-size:12px;
  font-weight:800;
  margin-top:1px;
}
.tag{
  display:inline-block;
  padding:3px 10px;
  border-radius:100px;
  background:var(--accent-dim);
  color:var(--accent);
  font-size:12px;
  font-weight:700;
}
.footer{
  padding:36px 0 56px;
  text-align:center;
  color:var(--text3);
  font-size:13px;
  border-top:1px solid var(--border);
}

/* Responsive: 실제 그리드 클래스는 좁은 뷰포트에서 단일 열로 쌓는다. */
@media(max-width:900px){
  .grid-2,.grid-3,.grid-4{grid-template-columns:1fr}
}
@media(max-width:700px){
  .compare{grid-template-columns:1fr}
}
@media(max-width:600px){
  .page{padding:0 16px}
  section{padding:48px 0}
  .hero{padding:40px 0 48px}
  .grid-2,.grid-3,.grid-4{grid-template-columns:1fr}
  .workflow{align-items:stretch;flex-direction:column;gap:8px}
  .workflow-arrow{transform:rotate(90deg);margin:0;text-align:center}
  .workflow-item{text-align:center}
  .card,.compare-panel{padding:22px}
}
</style>
</head>
<body>
<button class="theme-toggle" id="theme-btn" type="button" onclick="toggleTheme()" aria-label="테마 전환">라이트</button>
<div class="page">

<header class="hero">
  <div class="hero-badge">Design Kit · Skill Guide</div>
  <h1>디자인 목업</h1>
  <p>특정 화면을 위한 하이파이 HTML 시안을 만들되, 먼저 개수와 차별화 축을 계약하고 선택 이후의 수정·승인·전송까지 추적 가능하게 운영한다.</p>
  <div class="hero-meta" aria-label="핵심 규칙">
    <span class="pill">미지정 최소 5안</span>
    <span class="pill">위 제한 없음</span>
    <span class="pill">standalone HTML</span>
    <span class="pill">전역 유니크 ID</span>
  </div>
</header>

<main>
<section aria-labelledby="overview-title">
  <div class="section-label">Workflow</div>
  <h2 class="section-title" id="overview-title">탐색에서 승인 기록까지</h2>
  <p class="section-desc">디자인 컨셉과 토큰을 자동 감지하고, 합의된 전략별 시안을 생성한 뒤 사용자의 선택을 정확한 ID와 승인 기록으로 남긴다.</p>
  <div class="workflow" aria-label="디자인 워크플로우">
    <span class="workflow-item">design-concept</span>
    <span class="workflow-arrow" aria-hidden="true">→</span>
    <span class="workflow-item">design-system</span>
    <span class="workflow-arrow" aria-hidden="true">→</span>
    <span class="workflow-item active">design-mockup</span>
    <span class="workflow-arrow" aria-hidden="true">→</span>
    <span class="workflow-item">design-component</span>
  </div>
</section>

<section aria-labelledby="principles-title">
  <div class="section-label">Core Principles</div>
  <h2 class="section-title" id="principles-title">목업을 지탱하는 네 가지 원칙</h2>
  <p class="section-desc">보기 좋은 화면보다 비교 가능하고 추적 가능하며 구현으로 안전하게 이어지는 시안을 우선한다.</p>
  <div class="grid-4">
    <article class="card principle-card">
      <div class="card-title"><span class="num">01</span>먼저 계약한다</div>
      <p>파일 생성 전에 Variant Contract Matrix의 6개 열과 산출 개수를 사용자와 합의한다. 색상만 다른 안은 별도 시안이 아니다.</p>
      <a class="card-source" href="../../design-kit/references/visual-change-protocol.md">출처: Visual Change Protocol §5</a>
    </article>
    <article class="card principle-card">
      <div class="card-title"><span class="num">02</span>시각 원본을 보존한다</div>
      <p>브라우저에서 승인된 색상·간격·타이포 값은 기존 토큰보다 우선한다. 토큰화가 필요하면 값을 바꾸지 않고 그 값으로 토큰을 정의한다.</p>
      <a class="card-source" href="../../design-kit/references/visual-change-protocol.md">출처: Visual Change Protocol §1</a>
    </article>
    <article class="card principle-card">
      <div class="card-title"><span class="num">03</span>접근성을 기본값으로 둔다</div>
      <p>WCAG 2.2 AA 대비 4.5:1과 24×24 CSS px 최소 타겟을 지킨다. 시안 기본은 AAA와 플랫폼 권장치인 44×44 CSS px로 잡는다.</p>
      <a class="card-source" href="https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html">출처: W3C WCAG 2.2 SC 2.5.8</a>
    </article>
    <article class="card principle-card">
      <div class="card-title"><span class="num">04</span>증거 채널을 구분한다</div>
      <p>목업 캡처는 artifact_snapshot이다. 실제 앱 화면의 정상 동작을 주장하려면 별도 런타임 증거가 필요하다.</p>
      <a class="card-source" href="../../design-kit/references/visual-change-protocol.md">출처: Visual Change Protocol §7</a>
    </article>
  </div>
</section>

<section aria-labelledby="numbers-title">
  <div class="section-label">Numbers</div>
  <h2 class="section-title" id="numbers-title">판단에 쓰는 수치 기준</h2>
  <p class="section-desc">원본 스킬에 명시된 개수·차이·접근성·호환성 기준만 모았다.</p>
  <div class="table-wrap">
    <table>
      <thead>
        <tr>
          <th>항목</th>
          <th>기준</th>
          <th>적용 방식</th>
        </tr>
      </thead>
      <tbody>
        <tr><td>사용자 지정 시안</td><td>정확히 N개</td><td>초과와 미달 모두 계약 위반</td></tr>
        <tr><td>개수 미지정</td><td>최소 5개</td><td>비교에 더 필요하면 더 낸다</td></tr>
        <tr><td>위 제한</td><td>없음</td><td>위 제한 없이 필요한 만큼. 여섯째부터 틀에 칸 묶음을 더한다</td></tr>
        <tr><td>구별성: 지정 축 3개 이상</td><td>모든 쌍의 Hamming distance ≥ 2</td><td>겹치는 시안은 제출 전 재설계</td></tr>
        <tr><td>구별성: 지정 축 2개 이하</td><td>모든 쌍의 Hamming distance ≥ 1</td><td>카피·아이콘·색 변경은 축으로 세지 않음</td></tr>
        <tr><td>텍스트 대비</td><td>WCAG 2.2 AA 4.5:1</td><td>하이파이 시안에도 동일 적용</td></tr>
        <tr><td>터치 타겟</td><td>AA 24×24 / AAA 44×44 CSS px</td><td>시안 기본은 44×44, Apple HIG 권장은 44pt</td></tr>
        <tr><td>컴포넌트 ID</td><td>4자리 해시</td><td><code>{컴포넌트명}-{4자리해시}</code>, 전역 유니크</td></tr>
        <tr><td>Container Queries 지원 시작</td><td>Chrome 105 · Firefox 110 · Safari 16</td><td>style·scroll-state 쿼리는 지원 범위가 다름</td></tr>
        <tr><td>수정 반복</td><td>스스로 고치기 최대 3회</td><td>비교 반복 순서와 캡처 점검 목록을 따름</td></tr>
      </tbody>
    </table>
  </div>
</section>

<section aria-labelledby="step0-title">
  <div class="section-label">Step 0</div>
  <h2 class="section-title" id="step0-title">Step 0: 자동 감지 및 로드</h2>
  <p class="section-desc">프로젝트에서 이전 단계 산출물을 탐색한다. 이미 합의된 컨셉 · 토큰 · 승인 기록 · 비범위 표를 먼저 읽어 새 시안의 입력으로 삼는다.</p>
  <pre><code># 감지 대상
.design/concept.md          → 컨셉 로드
**/theme/** **/tokens/**    → 디자인 토큰 로드
**/design-tokens.*          → 디자인 토큰 로드
.design/approvals/*.md      → 같은 화면의 확정 구성 · 폐기한 대안 로드
.planning/prd-*.md          → 비범위 표(## Non-goals (폐기한 결정 포함) · ## No-gos)의 폐기한 결정 로드</code></pre>
  <div class="grid-2" style="margin-top:24px">
    <article class="card">
      <div class="card-title"><span class="dot"></span>찾은 입력의 적용</div>
      <ul>
        <li>컨셉 존재 → 무드 키워드, 컬러/타이포 방향, UI 패턴을 시안에 반영</li>
        <li>토큰 존재 → 구체적 컬러값, 타이포 스케일, 간격을 시안에 적용</li>
        <li>둘 다 없음 → 사용자 요구사항만으로 시안 생성</li>
        <li>승인 기록 존재 → 확정 구성을 지키고, 폐기한 대안·요소는 사용자가 되살리라고 하지 않는 한 시안에 다시 넣지 않는다 (<code>../../references/visual-change-protocol.md</code> §4)</li>
        <li>PRD 비범위 표 존재 → 그 표의 항목은 시안에 넣지 않는다. 코드에 흔적이 남아 있어도 요구로 읽지 않고, 되살려야 할 것 같으면 만들기 전에 사용자에게 묻는다 (planning-kit plan-prd Gotcha 14)</li>
      </ul>
    </article>
    <article class="card">
      <div class="card-title"><span class="dot"></span>승인 기록 폐기 칸이 경로를 가리킴</div>
      <p>그 파일을 열어 원문을 읽는다. PRD 경로면 비범위 표 항목을, 작업 계약 경로면 <code>범위 경계</code> 에서 줄 끝이 <code>PRD 없음</code> 인 줄을 폐기 항목으로 쓰고 시안에 넣지 않는다.</p>
      <p style="margin-top:10px">파일이 없거나 못 읽으면(추적하지 않는 <code>.harness</code> 는 새 워크트리에 따라오지 않는다) <code>못 읽음: &lt;경로&gt;</code> 를 말하고 시안을 만들기 전에 사용자에게 묻는다.</p>
    </article>
  </div>
  <div class="note"><strong>앱 코드가 있을 때:</strong> §0 관례 표는 Step 1 에서 대상 화면을 정한 뒤에 만든다 — 대상이 없으면 「같은 역할」 을 고를 수 없다. 같은 역할의 서로 다른 기존 화면을 §0 이 정한 개수만큼 읽고(기준 원본 harness <code>skill-design-guide.md</code> §8.9), 재사용 부품은 grep 으로 확인한 실제 이름만 쓴다. 관례는 Step 2-a 매트릭스의 <code>constants</code> 에 넣는다.</div>
</section>

<section aria-labelledby="step1-title">
  <div class="section-label">Step 1</div>
  <h2 class="section-title" id="step1-title">Step 1: 화면 요구사항 파악</h2>
  <p class="section-desc">사용자의 요청에서 파악한다 — 어떤 화면인지, 무엇을 해야 하는지, 누가 쓰는지를 먼저 고정한다. 불명확하면 사용자에게 확인한다.</p>
  <div class="grid-3">
    <article class="card">
      <div class="card-title"><span class="dot"></span>페이지와 화면</div>
      <p>어떤 페이지/화면인지 (로그인, 대시보드, 설정 등). 대상 화면의 파일 경로와 라우트도 함께 적고, 새 화면이면 <code>신규</code> 라고 표시한다.</p>
    </article>
    <article class="card">
      <div class="card-title"><span class="dot"></span>기능과 정보</div>
      <p>주요 기능과 정보 요소. 요청을 요소 이름과 배치까지 넣어 되말한 한 문장으로 남긴다.</p>
    </article>
    <article class="card">
      <div class="card-title"><span class="dot"></span>대상 사용자</div>
      <p>누가 어떤 맥락에서 쓰는지 확인한다. 두 갈래로 읽히면 묻고 시작한다.</p>
    </article>
  </div>
  <div class="note"><strong>파일을 만들기 전에:</strong> <code>../../references/visual-change-protocol.md</code> §0 의 대상과 되말하기를 응답에 남긴다 — 대상 화면의 파일 경로와 라우트(새 화면이면 <code>신규</code>), 그리고 요청을 요소 이름과 배치까지 넣어 되말한 한 문장.</div>
</section>

<section aria-labelledby="step2-title">
  <div class="section-label">Step 2</div>
  <h2 class="section-title" id="step2-title">Step 2: 개수 계약 · Variant Contract Matrix 합의 후 하이파이 HTML 시안 생성</h2>
  <p class="section-desc">파일을 만들기 전에 개수와 차별화 축을 고정하고, 구별성 게이트를 통과한 시안만 생성한다.</p>

  <h3 class="subhead">Step 2-a · 개수와 축을 먼저 고정한다 (파일을 만들기 전에)</h3>
  <p class="section-desc"><code>../../references/visual-change-protocol.md</code> §5 Variant Contract Matrix 를 채워 사용자와 합의한다. 개수 규칙 · 축 개수 · 부대 산출물 금지의 기준 원본은 <code>harness/docs/guides/skill-design-guide.md</code> §5.6 이다.</p>
  <div class="table-wrap">
    <table>
      <thead><tr><th>상황</th><th>산출 개수</th></tr></thead>
      <tbody>
        <tr><td>사용자가 개수를 말함</td><td><strong>정확히 그 수</strong> — 초과도 미달도 위반</td></tr>
        <tr><td>미지정</td><td><strong>최소 5</strong> — 비교에 더 필요하면 더 낸다. 위 제한 없음</td></tr>
      </tbody>
    </table>
  </div>
  <div class="table-wrap" style="margin-top:18px">
    <table>
      <thead>
        <tr>
          <th>variant_id</th>
          <th>strategy_label</th>
          <th>axis_vector</th>
          <th>constants</th>
          <th>intended_user_scenario</th>
          <th>생성 파일</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>시안 식별자</td>
          <td>전략적 우선순위</td>
          <td>비교할 구조 축의 값</td>
          <td>모든 안에서 고정할 관례</td>
          <td>가장 잘 맞는 사용자 맥락</td>
          <td>standalone HTML 경로</td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="note"><strong>구별성 자가 검사:</strong> 매트릭스 6 열(<code>variant_id</code> · <code>strategy_label</code> · <code>axis_vector</code> · <code>constants</code> · <code>intended_user_scenario</code> · 생성 파일)을 채운 뒤 통과시킨다 — 지정 축이 3 개 이상이면 모든 쌍의 Hamming distance ≥ 2, 2 개 이하면 ≥ 1. 실행 가능한 게이트가 §5 에 있다. 겹치는 쌍이 있으면 그 세트는 제출하지 말고 겹치는 쪽을 다시 설계한다 (글로벌 REJECT <code>UI-04</code>). 요청받지 않은 토큰 파일·디자인 시스템·서페이스 레인·컴포넌트 카탈로그는 <strong>만들지 않는다.</strong> 필요해 보이면 별도 제안으로 올리고 승인 후에 만든다.</div>

  <h3 class="subhead">Step 2-b · 합의된 개수만큼 생성</h3>
  <p class="section-desc">references/mockup-guidelines.md를 참조하고 ../../templates/mockup.html 포맷으로 시안을 생성한다. 각 시안은 standalone HTML 파일로 생성한다.</p>
  <div class="grid-3">
    <article class="card">
      <div class="eyebrow">OUTPUT</div>
      <div class="card-title">standalone 하이파이 HTML</div>
      <p><code>.design/mockups/{페이지명}-{특징}.html</code> (예: <code>dashboard-sidebar.html</code>). 실제 컬러, 타이포, 간격이 반영된 하이파이 수준으로 만든다. lorem ipsum 금지 — 실제 콘텐츠 또는 현실적 예시 데이터 사용.</p>
    </article>
    <article class="card">
      <div class="eyebrow">TRACEABILITY</div>
      <div class="card-title">모든 UI 요소에 ID</div>
      <p>모든 UI 요소에 <code>{컴포넌트명}-{4자리해시}</code> ID 부여. 전체 시안에 걸쳐 해시가 겹치면 재생성한다. 호버 시 ID를 표시하는 JavaScript 오버레이 포함.</p>
    </article>
    <article class="card">
      <div class="eyebrow">RESPONSIVE</div>
      <div class="card-title">상태와 규칙을 함께 제시</div>
      <p>반응형이 요구사항에 포함된 경우, 각 시안에 mobile/tablet/desktop breakpoint 섹션을 추가하고 컬럼 수·거터·max-width 규칙을 명시한다.</p>
    </article>
  </div>
  <div class="note"><strong>여섯째 시안부터:</strong> 틀은 시안 칸 A~E 다섯을 기본으로 둔다. 여섯째 시안부터는 칸 묶음을 f, g … 순서로 하나씩 더한다 — 탭 버튼 · 패널 · 비교 선택 두 곳의 option · 투표 카드 · 메모 칸 · <code>MOCKUP_CONFIG.variants</code> 항목 · <code>T.ko.tab</code> / <code>T.en.tab</code> 글자. 틀 스크립트는 시안 목록을 <code>MOCKUP_CONFIG.variants</code> 에서만 읽으므로 스크립트는 고치지 않는다.</div>

  <h3 class="subhead">전략 레이블 후보 풀</h3>
  <p class="section-desc"><code>strategy_label</code> 후보 풀이다. 합의된 개수만큼 <strong>골라 쓴다</strong>. 합의한 수가 풀보다 많으면 요청 화면에 맞는 풀 밖 전략을 더 만든다 — 이 목록은 예시이지 한계가 아니다.</p>
  <div class="grid-3">
    <article class="card"><span class="tag">전환 최적화형</span><p style="margin-top:12px">사이드바 네비게이션 + 메인 콘텐츠, 주요 CTA를 상단 고정.</p></article>
    <article class="card"><span class="tag">탐색성 강화형</span><p style="margin-top:12px">탑바 + 카드 그리드, 필터/정렬 전면 배치.</p></article>
    <article class="card"><span class="tag">정보 밀도형</span><p style="margin-top:12px">탭 기반 + 리스트 뷰, 스캔 가능한 텍스트 계층 강조.</p></article>
    <article class="card"><span class="tag">브랜드 임팩트형</span><p style="margin-top:12px">풀스크린 히어로 + 스크롤 섹션, 비주얼 중심 진입.</p></article>
    <article class="card"><span class="tag">대시보드/제어형</span><p style="margin-top:12px">위젯 패널 레이아웃, 상태 요약 + 빠른 액션 우선.</p></article>
    <article class="card"><span class="tag">풀 밖 전략</span><p style="margin-top:12px">합의한 수가 다섯보다 많으면 요청 화면에 맞는 전략을 새로 더한다. 새 전략도 구별성 검사를 똑같이 통과해야 한다.</p></article>
  </div>

  <h3 class="subhead">반응형 구현 원칙</h3>
  <div class="grid-2">
    <article class="card">
      <div class="card-title"><span class="dot"></span>Container Queries</div>
      <p>페이지 레벨 분기는 media queries, 컴포넌트 레벨 분기는 <code>container-type: inline-size</code> + <code>@container</code> queries를 사용한다. 디바이스 이름보다 콘텐츠가 깨지는 지점에 breakpoint를 둔다. cqw/cqi 유닛으로 컨테이너 상대 크기 지정이 가능하다.</p>
    </article>
    <article class="card">
      <div class="card-title"><span class="dot"></span>Fluid Typography</div>
      <p><code>clamp(min, preferred, max)</code> 기반 fluid font-size로 breakpoint 없이 모든 뷰포트에서 자연스러운 크기 전환을 보여준다. 특히 히어로/디스플레이 텍스트에 효과적이다.</p>
    </article>
  </div>
</section>

<section aria-labelledby="step3-title">
  <div class="section-label">Step 3</div>
  <h2 class="section-title" id="step3-title">Step 3: 디자인 의도 설명</h2>
  <p class="section-desc">발표 순서는 "화면 나열"이 아니라 사용자 시나리오 흐름으로 구성한다. 각 시안을 독립적으로 설명하기보다, 어떤 문제를 어떻게 다르게 해결하는지 대비하여 설명하면 선택 기준 토론이 쉬워진다.</p>
  <div class="grid-3">
    <article class="card">
      <div class="card-title"><span class="num">1</span>전략과 구조</div>
      <p>시안이 반영한 전략적 우선순위 (전환, 탐색, 브랜드 등)와 레이아웃 선택 이유와 정보 구조.</p>
    </article>
    <article class="card">
      <div class="card-title"><span class="num">2</span>시선과 맥락</div>
      <p>시각적 강조 포인트 — 어디서 시선이 머무는가. 어떤 사용자 시나리오/맥락에 가장 잘 맞는가.</p>
    </article>
    <article class="card">
      <div class="card-title"><span class="num">3</span>결정 근거</div>
      <p>주요 결정의 간단한 근거 (왜 이 구성인가). 취향 투표가 아니라 선택 기준에 관한 토론으로 만든다.</p>
    </article>
  </div>
</section>

<section aria-labelledby="step4-title">
  <div class="section-label">Step 4</div>
  <h2 class="section-title" id="step4-title">Step 4: 사용자 선택 및 수정</h2>
  <p class="section-desc">사용자가 시안을 선택하거나 피드백을 준다. ID를 사용해 소통한다: "card-product-a3f2를 더 크게 해줘". 시안 간 비교 요청 시 비교 기법을 고른다.</p>
  <div class="table-wrap">
    <table>
      <thead><tr><th>비교 상황</th><th>기법</th></tr></thead>
      <tbody>
        <tr><td>구조가 크게 다른 안 비교</td><td>side-by-side (나란히 배치)</td></tr>
        <tr><td>동일 화면 일부 요소 변경 비교</td><td>변경 전/후를 겹쳐서 설명</td></tr>
        <tr><td>결정 근거/핸드오프 포함 비교</td><td>주석(annotation) 추가</td></tr>
        <tr><td>인터랙션·상태 변화 비교</td><td>hover/focus/click 동작 포함</td></tr>
      </tbody>
    </table>
  </div>
  <h3 class="subhead">Change Manifest</h3>
  <p class="section-desc">수정 요청이 <strong>속성 하나나 요소 하나를 지목한 경우</strong>(보더만·색만·간격만, 이 칩만) 편집 전에 Change Manifest 를 남긴다 (Gotcha 15 · <code>../../references/visual-change-protocol.md</code> §2).</p>
  <pre><code>## Change Manifest
- 변경: [속성 — 대상 ID — 현재값 → 목표값]
- 보존: [같은 요소의 나머지 시각 속성 — background / fill / radius / shadow / spacing / typography 중 해당분 · 요소 하나를 지목했으면 같은 줄·같은 영역의 이웃 요소와 그 자리]</code></pre>
  <p class="note"><strong>수정 후:</strong> 보존 목록의 값이 그대로인지 확인한다. 변했으면 되돌리고 지목된 속성만 다시 적용한다. 고치는 순서 · 반영 확인 · 스스로 고치기 횟수 상한은 §3 비교 반복 순서를 따르고(기준 원본 harness <code>skill-design-guide.md</code> §8.9), 캡처마다 §3 캡처 점검 목록을 본다. 수정 후 HTML 파일을 갱신하고, 확정 시 <code>.design/mockups/</code> 에 최종본 유지.</p>
</section>

<section aria-labelledby="step5-title">
  <div class="section-label">Step 5</div>
  <h2 class="section-title" id="step5-title">Step 5: 승인 기록 생성 (확정 시 필수)</h2>
  <p class="section-desc">사용자가 시안을 확정하면 <code>.design/approvals/{YYYYMMDD}-{화면명}.md</code> 를 생성한다. 대화 로그만으로는 이후 QA 에서 승인 근거를 확인할 수 없어 REJECT 된다 (Gotcha 13 · 글로벌 <code>UI-06</code>).</p>
  <pre><code># 승인 기록 — {화면명}

- 승인일: {YYYY-MM-DD}
- 승인 주체: {사용자 직접 확정 | 자율 모드 (판단 근거 명시)}
- 대상 산출물: .design/mockups/{파일명}.html
- 선택된 안: {전략 레이블 + 시안 ID}
- 확정된 시각 값: {승인 시점에 고정된 색상·타이포·간격 — 이후 토큰과 충돌 시 이 값이 우선}
- 확정 구성: {화면에 남는 요소와 배치}
- 폐기한 대안·이유: {버린 안·요소와 이유 — 기능·설정 항목을 없앤 결정이면 이유는 여기 다시 쓰지 않는다. 그 기능 PRD 비범위 표 경로와 그 줄의 「하지 않는 것」 만 적는다 (planning-kit plan-prd Gotcha 14) · 없으면 `없음`}
- 미확정/후속: {합의되지 않아 남긴 항목}
- 원문 근거: {사용자 발화 인용}</code></pre>
  <h3 class="subhead">PRD 가 없을 때 결정 원문을 두는 자리</h3>
  <div class="table-wrap">
    <table>
      <thead><tr><th>그 기능에 있는 것</th><th>결정 원문의 자리</th><th>폐기 칸에 적는 것</th></tr></thead>
      <tbody>
        <tr><td>PRD(<code>.planning/prd-&lt;slug&gt;.md</code>)</td><td>PRD 비범위 표</td><td>그 표 경로와 그 줄의 「하지 않는 것」</td></tr>
        <tr><td>PRD 없음 · 작업 계약 있음</td><td>작업 계약 <code>범위 경계</code> 한 곳 — 네 칸(하지 않는 것 · 이유 · 범위 · 코드에 남은 흔적), 줄 끝에 <code>PRD 없음</code></td><td>그 계약 경로만</td></tr>
        <tr><td>PRD 도 작업 계약도 없음</td><td>이 승인 기록 폐기 칸 한 곳</td><td>같은 네 칸을 결정 하나에 한 줄씩 폐기 칸 아래에 들여써 <code>-</code> 로 시작하는 목록 항목으로, 줄 끝에 <code>PRD 없음</code></td></tr>
      </tbody>
    </table>
  </div>
  <div class="note">그 기능의 PRD(<code>.planning/prd-&lt;slug&gt;.md</code>)가 없으면 결정 원문은 작업 계약 <code>범위 경계</code> 한 곳에 plan-prd 비범위 표와 같은 네 칸(하지 않는 것 · 이유 · 범위 · 코드에 남은 흔적)으로 적고 줄 끝에 <code>PRD 없음</code> 을 붙인다. 폐기 칸에는 그 계약 경로만 적는다 — 결정 원문이 두 곳에 있으면 한쪽만 고쳐진다 (<code>../../references/visual-change-protocol.md</code> §4). 그 기능의 작업 계약도 없으면 결정 원문은 이 승인 기록 폐기 칸 한 곳이다 — 같은 네 칸을 결정 하나에 한 줄씩 폐기 칸 아래에 들여써 <code>-</code> 로 시작하는 목록 항목으로 적고 줄 끝에 <code>PRD 없음</code> 을 붙인다. 다음 시안 전에는 Step 0 이 폐기 칸의 경로를 따라 원문을 읽는다. 폐기 기록만 담으려고 PRD 를 만들지 않는다 (plan-prd Gotcha 1).</div>
  <h3 class="subhead">생성 직후 검증</h3>
  <pre><code>ls .design/approvals/                      # 파일 존재
grep -c '확정된 시각 값' .design/approvals/{파일명}.md   # → 1
grep -cE '^- (확정 구성|폐기한 대안·이유):' .design/approvals/{파일명}.md   # → 2</code></pre>
  <div class="note"><strong>승인 후 다시 수정했다면:</strong> 승인 후 시안을 다시 수정하면 이 기록도 갱신한다. 스테일 승인 기록은 없는 것보다 나쁘다.</div>
</section>

<section aria-labelledby="step6-title">
  <div class="section-label">Step 6</div>
  <h2 class="section-title" id="step6-title">Step 6: Figma 전송 (선택)</h2>
  <p class="section-desc">사용자가 Figma 전송을 요청하면 먼저 Figma MCP 설정을 확인한다.</p>
  <div class="grid-3">
    <article class="card">
      <div class="eyebrow">CONNECTED</div>
      <div class="card-title">설정됨</div>
      <p>선택한 시안 또는 개별 컴포넌트(ID 기준)를 Figma로 전송한다.</p>
    </article>
    <article class="card">
      <div class="eyebrow">NOT CONFIGURED</div>
      <div class="card-title">미설정</div>
      <p>에러를 내지 않고 “Figma 전송을 원하면 Figma MCP 설정이 필요합니다” 안내 + HTML 파일 경로 재안내.</p>
    </article>
    <article class="card">
      <div class="eyebrow">FAILED</div>
      <div class="card-title">전송 실패</div>
      <p>에러 메시지 + HTML 파일 경로 안내.</p>
    </article>
  </div>
</section>

<section aria-labelledby="anti-title">
  <div class="section-label">Anti-patterns</div>
  <h2 class="section-title" id="anti-title">나쁜 비교와 좋은 비교</h2>
  <p class="section-desc">형식적으로 여러 안을 만드는 대신, 계산 가능한 구조 차이와 명확한 선택 근거를 만든다.</p>
  <div class="compare">
    <article class="compare-panel compare-bad">
      <div class="compare-label">Bad</div>
      <h3>A안 / B안, 색상만 교체</h3>
      <p>레이아웃과 구성 축은 같은데 accent, 카피, 아이콘만 바꾸고 별도 시안이라고 선언한다.</p>
      <ul>
        <li><code>axis_vector</code>의 Hamming distance는 0</li>
        <li>전략 레이블이 없어 취향 투표로 흐름</li>
        <li>요청하지 않은 토큰 파일과 카탈로그까지 생성</li>
        <li>정적 캡처로 인터랙션 정상까지 주장</li>
      </ul>
    </article>
    <article class="compare-panel compare-good">
      <div class="compare-label">Good</div>
      <h3>전환 최적화형 / 탐색성 강화형</h3>
      <p>합의한 네비게이션·콘텐츠 구조·정보 위계 축을 실제로 달리하고, 같은 사용자 시나리오에서 비교한다.</p>
      <ul>
        <li>모든 시안 쌍이 구별성 게이트 통과</li>
        <li>전략과 적합한 사용자 맥락을 함께 설명</li>
        <li>계약된 개수와 HTML 파일만 생성</li>
        <li>artifact_snapshot과 앱 런타임 증거를 구분</li>
      </ul>
    </article>
  </div>
  <h3 class="subhead">부분 수정의 bad / good</h3>
  <div class="compare">
    <article class="compare-panel compare-bad">
      <div class="compare-label">Bad</div>
      <h3>“보더만” 요청에 전체 스타일 정규화</h3>
      <p>승인된 색을 기존 accent 토큰으로 바꾸고 radius, shadow, spacing까지 함께 손본다. 요청하지 않은 변화는 개선이 아니라 실패다.</p>
    </article>
    <article class="compare-panel compare-good">
      <div class="compare-label">Good</div>
      <h3>Change Manifest로 한 축만 변경</h3>
      <p>대상 ID와 현재값·목표값을 적고, 배경·채움·반경·그림자·간격·타이포 및 이웃 요소의 자리를 보존 목록으로 검증한다.</p>
    </article>
  </div>
</section>

<section aria-labelledby="gotchas-title">
  <div class="section-label">Gotchas</div>
  <h2 class="section-title" id="gotchas-title">제출 전 체크리스트</h2>
  <p class="section-desc">원본의 17개 주의사항을 원문 그대로 옮겼다. 제출 전에 빠짐없이 점검한다.</p>
  <ol class="checklist">
    <li><span class="check">1</span><span><strong>컬러 변형만으로 시안 구분 금지 — 구별성은 선언이 아니라 계산이다</strong> — 시안들은 서로 다른 레이아웃/구성 접근이어야 한다. 색상·토큰 값·카피 문구·아이콘 교체는 <code>axis_vector</code> 원소로 세지 않으므로, 그것만 다른 두 안은 Hamming distance 0 이며 FAIL 이다. 판정식과 실행 가능한 게이트: <code>../../references/visual-change-protocol.md</code> §5 Variant Contract Matrix. 실측 근거는 글로벌 REJECT <code>UI-04</code> — 계약이 4 축을 <strong>이미 명시</strong>했는데도 두 안이 전 축 동일값이었다.</span></li>
    <li><span class="check">2</span><span><strong>ID 중복 금지</strong> — 생성한 전 시안에 걸쳐 모든 컴포넌트 ID는 전역 유니크여야 한다. <code>{컴포넌트명}-{짧은해시}</code> 포맷을 사용하라. 같은 해시가 나오면 재생성한다.</span></li>
    <li><span class="check">3</span><span><strong>접근성 원칙 무시 금지</strong> — 하이파이 시안이라도 WCAG 2.2 AA 대비 비율(4.5:1)과 최소 터치 타겟을 준수하라. <strong>WCAG 2.2 SC 2.5.8 AA = 24×24 CSS px</strong> / SC 2.5.5 AAA = 44×44 CSS px / Apple HIG 44pt는 터치 디바이스 실용 권장치다. 시안에서 AAA/플랫폼 권장 44pt를 기본으로 잡아두면 Figma/HTML → 코드 단계에서 안전하다. 시각적으로 예뻐도 접근성 위반이면 안 된다. 출처: <a href="https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html">W3C WCAG 2.2 SC 2.5.8</a>.</span></li>
    <li><span class="check">4</span><span><strong>Figma MCP 미설정 시 에러 금지</strong> — Figma 전송 요청 시 MCP가 미설정이면 에러가 아닌 안내로 처리하라. "Figma 전송을 원하면 Figma MCP 설정이 필요합니다"와 함께 HTML 파일 경로를 안내한다.</span></li>
    <li><span class="check">5</span><span><strong>Lorem ipsum 금지</strong> — 플레이스홀더 텍스트는 실제 사용자가 마주칠 콘텐츠와 다르게 읽힌다. 실제 콘텐츠나 현실적인 예시 데이터를 사용하라. 제목, 버튼 레이블, 설명문이 lorem ipsum이면 레이아웃 의도를 제대로 평가할 수 없다.</span></li>
    <li><span class="check">6</span><span><strong>시안 레이블을 "A안/B안"으로만 붙이지 마라</strong> — 각 시안은 서로 다른 전략적 우선순위를 반영해야 한다. 레이블도 그 의도를 담아라. 예: <code>전환 최적화형</code>, <code>탐색성 강화형</code>, <code>브랜드 임팩트형</code>. 이렇게 하면 취향 투표가 아닌 선택 기준 토론으로 유도된다.</span></li>
    <li><span class="check">7</span><span><strong>디바이스 프레임은 목적에 따라 선택적으로 사용하라</strong> — 클라이언트 발표나 near-final 데모에는 디바이스 프레임이 완성 인상을 준다. 그러나 레이아웃 구조 비교나 콘텐츠 밀도 검토가 목적이면 프레임 없이 보여주는 편이 낫다. 프레임 chrome이 실제 논점인 레이아웃 판단을 방해할 수 있다.</span></li>
    <li><span class="check">8</span><span><strong>인터랙션이 쟁점이면 정적 비교에 의존하지 마라</strong> — 드롭다운, 오버레이, 멀티스텝 플로우, 로딩 상태, 모달 전환은 나란히 놓인 정지 화면만으로 판단하기 어렵다. HTML 시안에 hover/focus/click 인터랙션을 포함하거나, 인터랙티브 프로토타입 링크를 함께 제공하라.</span></li>
    <li><span class="check">9</span><span><strong>반응형 시안은 breakpoint별 스냅샷만으로 끝내지 마라</strong> — mobile/tablet/desktop 3단 구성을 보여줄 때, 각 화면에서 동일한 유저 시나리오 상태를 맞춰 두어야 비교가 의미 있다. 컬럼 수, 거터, max-width 등 레이아웃 규칙도 함께 명시하라.</span></li>
    <li><span class="check">10</span><span><strong>Container Queries 활용 권장</strong> — 반응형 시안에서 페이지 레벨 분기는 media queries, 컴포넌트 레벨 분기는 <code>container-type: inline-size</code> + <code>@container</code> queries를 사용하라. 크기 쿼리는 Chrome 105 · Firefox 110 · Safari 16 부터 지원한다 (style · scroll-state 쿼리는 지원 범위가 다르다). cqw/cqi 유닛으로 컨테이너 상대 크기 지정이 가능하다. 콘텐츠가 깨지는 지점에 breakpoint를 설정하고 디바이스 타겟 기반은 피하라. 출처: research-log §J.</span></li>
    <li><span class="check">11</span><span><strong>Fluid Typography 적용</strong> — 시안 내 텍스트에 <code>clamp(min, preferred, max)</code> 기반 fluid font-size를 적용하면 breakpoint 없이 모든 뷰포트에서 자연스러운 크기 전환을 보여줄 수 있다. 특히 히어로/디스플레이 텍스트에 효과적이다. 출처: research-log §E.</span></li>
    <li><span class="check">12</span><span><strong>mockup.html은 HTML 형식이 정상 산출물이다</strong> — 이 스킬의 출력물(<code>.design/mockups/*.html</code>)은 의도적으로 HTML 형식을 사용한다. <code>design-tokens.md</code>, <code>audit-report.md</code> 같은 <code>.md</code> 계약 패턴과 구조가 다른 것은 설계상 의도된 차이이며 오류가 아니다. QA 평가 또는 검증 도구가 "HTML 형식이 .md 패턴과 다르다"고 지적할 경우 False positive로 처리하고 이 Gotcha를 근거로 무시한다.</span></li>
    <li><span class="check">13</span><span><strong>확정 = 승인 기록 파일 생성 (대화 로그로 끝내지 마라)</strong> — 사용자가 시안을 확정하면 Step 5 에서 <code>.design/approvals/{YYYYMMDD}-{화면명}.md</code> 를 생성한다. 여기에 선택된 안, 산출물 경로, <strong>확정된 시각 값(색상·타이포·간격)</strong>, 원문 근거를 남긴다. 대화에서만 승인받고 파일을 남기지 않으면 이후 QA 에서 "goal 조건의 측정 근거(시안 승인 기록) 확인 불가" 로 REJECT 된다 — 2026-07-13 글로벌 REJECT <code>UI-06</code> 의 실제 사유다. <strong>자율 모드로 승인을 대행한 경우에도 기록을 남기고 승인 주체를 "자율 모드" 로 명시</strong>하라. 규격: <code>../../references/visual-change-protocol.md</code> §4.</span></li>
    <li><span class="check">14</span><span><strong>승인된 시안 값을 토큰으로 치환하지 마라 (Visual Source of Truth Precedence)</strong> — 사용자가 브라우저로 확인하고 승인한 시안의 색상·간격은 프로젝트 팔레트 토큰보다 <strong>우선한다</strong>. 시안 수정 요청을 처리할 때 승인된 값을 "토큰 체계에 맞춰" 단일 tint 나 기존 accent 로 정규화하지 마라. 토큰화가 필요하면 값을 바꾸는 게 아니라 <strong>그 값으로 토큰을 정의</strong>하고 별도 제안하라. 프로젝트에 이미 색상 체계가 있으면 새 팔레트를 도입하기 전에 기존 값을 먼저 열거해 제시한다. 우선순위 표: <code>../../references/visual-change-protocol.md</code> §1.</span></li>
    <li><span class="check">15</span><span><strong>부분 수정 요청은 그 속성만 — Change Manifest 필수</strong> — "이 카드 보더만 진하게", "색은 지금이 맞는데 그라디언트만 이전으로" 같은 요청에서 지목되지 않은 시각 속성(background, fill, radius, shadow, spacing, typography)을 함께 바꾸지 마라. 편집 전에 <code>변경 / 보존</code> 두 목록을 응답에 남기고, 수정 후 보존 목록의 값이 그대로인지 확인한다. 의도 외 영역이 변했으면 성공이 아니라 실패이므로 되돌리고 다시 적용한다. 부분 롤백 요청은 지목된 축만 되돌린다. 상세: <code>../../references/visual-change-protocol.md</code> §2.</span></li>
    <li><span class="check">16</span><span><strong>산출 전에 Variant Contract Matrix 를 합의하라 (개수 계약 + 구별성 게이트)</strong> — 시안을 하나라도 만들기 전에 <code>../../references/visual-change-protocol.md</code> §5 Variant Contract Matrix 6 열을 채워 사용자와 합의한다. 개수는 <strong>사용자가 말하면 정확히 그 수</strong>, 말하지 않으면 <strong>최소 5 개부터 위 제한 없이 필요한 만큼</strong> 낸다. 개수 규칙·primary axis 개수·부대 산출물(토큰 파일·디자인 시스템·서페이스 레인·카탈로그) 금지의 기준 원본은 <code>harness/docs/guides/skill-design-guide.md</code> §5.6 Variant Budget 이며 여기서 재정의하지 않는다. "몇 개 목업" 요청에 수십 타일과 토큰 파일을 함께 만들면 사용자가 전부 지우게 된다 — 실제로 그랬다.</span></li>
    <li><span class="check">17</span><span><strong>시안 캡처는 <code>artifact_snapshot</code> 이다 — 앱 화면 정상을 주장하지 마라</strong> — 목업 HTML 이 잘 열리는 것과 사용자가 실제 앱에서 그 화면을 보는 것은 다른 명제다. 증거를 인용할 때 채널 이름을 함께 적고, PASS 문장에 viewport · route/state · visible locator · count/height · screenshot id 5 요소를 넣어라. 채널 정의: <code>../../references/visual-change-protocol.md</code> §7 Evidence Channels. 사용자가 "아직 깨져 있다" 고 보고하면 반박하지 말고 재현하라 — 규약 정본은 <code>harness/docs/guides/skill-design-guide.md</code> §3.8 User-Reported Failure Gate 다.</span></li>
  </ol>
</section>

<section aria-labelledby="refs-title">
  <div class="section-label">References</div>
  <h2 class="section-title" id="refs-title">참조 문서</h2>
  <p class="section-desc">실행 세부 규칙과 산출 포맷의 정본이다.</p>
  <div class="grid-2">
    <article class="card">
      <div class="card-title"><span class="dot"></span>시안 생성 기준과 포맷</div>
      <ul>
        <li><a href="../../design-kit/skills/design-mockup/references/mockup-guidelines.md">references/mockup-guidelines.md</a> — 시안 생성 기준 상세</li>
        <li><a href="../../design-kit/templates/mockup.html">templates/mockup.html</a> — 공유 시안 HTML 출력 포맷</li>
      </ul>
    </article>
    <article class="card">
      <div class="card-title"><span class="dot"></span>계약과 증거의 정본</div>
      <ul>
        <li><a href="../../design-kit/references/visual-change-protocol.md">visual-change-protocol.md</a> — 시각 우선순위, 부분 변경, 승인, Variant Matrix, Evidence Channels</li>
        <li><a href="../../harness/docs/guides/skill-design-guide.md">skill-design-guide.md</a> — Variant Budget와 User-Reported Failure Gate</li>
      </ul>
    </article>
  </div>
</section>
</main>

<footer class="footer">
  Design Kit · design-mockup — 계약된 수의 구별 가능한 시안을 만들고, 선택과 승인을 추적한다.
</footer>
</div>
<script>
// 테마 — 저장 키 dk-theme. 저장값이 없으면 브라우저 색 설정을 따르고, 누를 때만 저장한다
function applyTheme(t){
  document.documentElement.setAttribute('data-theme', t);
  var btn = document.getElementById('theme-btn');
  if (btn) btn.textContent = t === 'dark' ? '라이트' : '다크';
}
function toggleTheme(){
  var next = document.documentElement.getAttribute('data-theme') === 'light' ? 'dark' : 'light';
  try { localStorage.setItem('dk-theme', next); } catch (e) {}
  applyTheme(next);
}
(function(){
  var saved = null;
  try { saved = localStorage.getItem('dk-theme'); } catch (e) {}
  applyTheme(saved || (matchMedia('(prefers-color-scheme: light)').matches ? 'light' : 'dark'));
})();
</script>
</body>
</html>
